### ISSUE TITLE
Migrate from mdl to material2

### ISSUE THREAD

**Issue by zolotyx** [bwsw/cloudstack-ui#265]
We need to get rid of MDL components.
Need to replace them by angular-material components

- [x] Select (mdl-select => md-select)
- [x] Tooltip (mdl-tooltip => mdTooltip)
- [x] Checkbox (mdl-checkbox => md-checkbox)
- [x] Radio (mdl-radio => md-radio)
- [x] Input (mdl-textfield => md-input-container)
- [x] Slider (mdl-slider => md-slider)
- [x] Progress Bar (mdl-progress => md-progress-bar)
- [x] Button, Fab (mdl-button => md-button, md-fab)
- [x] Icon (mdl-icon => md-icon)
- [x] Get rid of mdl classes (mdl-data-table)
- [x] MdlSnackbarService => MdSnackBar
- [x] Dialogs
- [x] Spinner (mdl-spinner => md-progress-spinner)
- [x] Card (mdl-card => md-card)
- [x] List (mdl-list => md-list)
- [x] Autocomplete
- [x] Table (mdl-data-table => md-table)
- [x] Popover

**Comment by wowshakhov** [comment]
closed in https://github.com/bwsw/cloudstack-ui/pull/516
