### ISSUE TITLE
Use ngrx store 

### ISSUE THREAD

**Issue by ershovaelena** [bwsw/cloudstack-ui#624]
We need to use ngrx store in the following sections:
- [x] VM list and Sidebar
- [x] VM creation 
- [x] Storage
- [x] Images 
- [x] Images creation and deleting
- [x] Firewall
- [x] Firewall creation and deleting
- [x] Activity Log
- [x] SSH keys
- [x] Accounts
